version: '3'
services:
  nginx:
    depends_on: 
      - client  
      - api     
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
  client:
    container_name: client
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    env_file: 
      - ./server/.env
    environment:
      - CHOKIDAR_USEPOLLING=true