export const SIGN_UP_WITH_EMAIL = 'SIGN_UP_WITH_EMAIL';
export const SIGN_UP_WITH_EMAIL_ERROR = 'SIGN_UP_WITH_EMAIL_ERROR';
export const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL';
export const LOGIN_WITH_EMAIL_ERROR = 'LOGIN_WITH_EMAIL_ERROR';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_WITH_TWITTER = 'LOGIN_WITH_TWITTER';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
