export const SIGN_UP_WITH_EMAIL = 'SIGN_UP_WITH_EMAIL';
export const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_WITH_TWITTER = 'LOGIN_WITH_TWITTER';
